### ISSUE TITLE
Wrong name / color picker is appears behind

### ISSUE THREAD

**Issue by michaeljota** [vedmack/angular-colorpicker#1]
Hi! Thanks for the color picker. It looks awesome. However, the name of the module is misspelled. Instead of 'color-picker-dr', the module name, getting from source, it's 'colorpicker-dr'.

**Comment by michaeljota** [comment]
Also, there is somehow to set the position of the picker? It apears to be always to down, and in my app, it loads into the background. (I'm using Angular Material toolbar to show the toolbar).

**Comment by vedmack** [comment]
Currently its not possible to control the position of the color picker ( I might add it in the future) but if loads into background It could be a z-index problem? If you'll provide a test case I can take look at it...

**Comment by michaeljota** [comment]
``` html
    <md-toolbar>
      <div class="md-toolbar-tools">
        <div>Color 1:</div>
        <div color-picker tiny-trigger="true" ng-model="vm.shape.LineColor">
        <div>Color 2:</div>
        <div color-picker tiny-trigger="true" ng-model="vm.shape.FillStyle">
      </div>
    </md-toolbar>
```

App:

``` javascript
angular
    .module('app', [
      'ngAnimate',
      'ngSanitize',
      'ngMessages',
      'ngAria',
      'ngMaterial',
      'ui.router',
      //components/plugins
      'colorpicker-dr'
      ]);
```

Also, do you plan to release this on bower? It would be great. :).

**Comment by vedmack** [comment]
I meant a test case like jsbin or jsfiddle, like the one I just found (google) http://jsfiddle.net/tiftof69/4b9smat2/, if you will construct a demo that shows how my color picker goes to background I will be able to help, as to the bower, please open a new issue for that...

**Comment by michaeljota** [comment]
https://jsbin.com/mazoqeguba/1/edit?html,js,output

You can see how the color picker it's show behind the toolbar.

**Comment by vedmack** [comment]
fixed, grab the [updated css file](https://github.com/vedmack/angular-colorpicker/blob/44d719ff058ce3cdb1892802a94026e3d1607d75/angular-colorpicker-dr.css)

**Comment by michaeljota** [comment]
Thanks!
