### ISSUE TITLE
Bower missing "main" and "ignore" entry.

### ISSUE THREAD

**Issue by michaeljota** [vedmack/angular-colorpicker#3]
When I install with bower, I get this warnings.

``` bash
bower invalid-meta  angular-colorpicker-dr is missing "main" entry in bower.json
bower invalid-meta  angular-colorpicker-dr is missing "ignore" entry in bower.json
```

If someone use a inyector or something like this, the task won't be able to inyect the angular-colorpicker itself. The bower need to have those fields, but it won't fail to install anyhow.

**Comment by vedmack** [comment]
main was there already ? anyway both there now...

**Comment by michaeljota** [comment]
Thanks! :)
